//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose.
        /// </summary>
        internal static string btnDiagnose {
            get {
                return ResourceManager.GetString("btnDiagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corona virus medical examination.
        /// </summary>
        internal static string HeadTitle {
            get {
                return ResourceManager.GetString("HeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a dry cough ?.
        /// </summary>
        internal static string lblCoughQuestion {
            get {
                return ResourceManager.GetString("lblCoughQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you suffer from diarrhea ?.
        /// </summary>
        internal static string lblDiarrheaQuestion {
            get {
                return ResourceManager.GetString("lblDiarrheaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a fever ?.
        /// </summary>
        internal static string lblFeverQuestion {
            get {
                return ResourceManager.GetString("lblFeverQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you suffer General ache and pains ?.
        /// </summary>
        internal static string lblGeneralAcheQuestion {
            get {
                return ResourceManager.GetString("lblGeneralAcheQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a headache ?.
        /// </summary>
        internal static string lblGeneralHeadacheQuestion {
            get {
                return ResourceManager.GetString("lblGeneralHeadacheQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For example, muscle aches).
        /// </summary>
        internal static string lblMuscleAche {
            get {
                return ResourceManager.GetString("lblMuscleAche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you suffer from a runny nose ?.
        /// </summary>
        internal static string lblRunnyNoseQuestion {
            get {
                return ResourceManager.GetString("lblRunnyNoseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you suffer Shortness of breath ?.
        /// </summary>
        internal static string lblShortnessBreathQuestion {
            get {
                return ResourceManager.GetString("lblShortnessBreathQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you suffer from sneezing ?.
        /// </summary>
        internal static string lblSneezingQuestion {
            get {
                return ResourceManager.GetString("lblSneezingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a sore throat ?.
        /// </summary>
        internal static string lblSoreThroatQuestion {
            get {
                return ResourceManager.GetString("lblSoreThroatQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you feel Fatigue, weakness ?.
        /// </summary>
        internal static string lblWeaknessQuestion {
            get {
                return ResourceManager.GetString("lblWeaknessQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes.
        /// </summary>
        internal static string Sometimes {
            get {
                return ResourceManager.GetString("Sometimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if you have symptoms of a coronavirus, just a cold, or a seasonal flu.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with the diagnosis by answering the following questions.
        /// </summary>
        internal static string SurveyBoxTitle {
            get {
                return ResourceManager.GetString("SurveyBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
